.TH "bug" 3 "Thu Jul 31 2014" "Version 1.0" "CIDGEL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBFile \fBbinomial\&.c\fP \fP" 1c
No known bugs  
.IP "\fBFile \fBbinomial\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBcall\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBcode\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBcode\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBexsearch\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBexsearch\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBgset\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBgset\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBmatch\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBmatch\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBmatrices\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBmatrices\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBreverse\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBreverse\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBRsimp\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fBRsimp\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fButils\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fButils\&.h\fP \fP" 1c
No known bugs 
.IP "\fBFile \fButime\&.c\fP \fP" 1c
No known bugs 
.IP "\fBFile \fButime\&.h\fP \fP" 1c
No known bugs
.PP

