.TH "utils.c" 3 "Thu Jul 31 2014" "Version 1.0" "CIDGEL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
utils.c \- 
.PP
A place for general global definitions which must be accessible througout the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBeatwhite\fP (FILE *is)"
.br
.RI "\fISkips all whitespaces when reading a file\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A place for general global definitions which must be accessible througout the program\&. 

This file is reused from TiGERS, Toric Groebner Basis Enumeration by Reverse Search copyright (c) 1999 Birk Huber
.PP
\fBAuthor:\fP
.RS 4
Birk Huber, 4/99 
.PP
Daniel Rembold 
.RE
.PP
\fBBug\fP
.RS 4
No known bugs
.RE
.PP

.PP
Definition in file \fButils\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int eatwhite (FILE *is)"

.PP
Skips all whitespaces when reading a file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIis\fP Input stream\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
0 for being successful 
.RE
.PP

.PP
Definition at line 20 of file utils\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CIDGEL from the source code\&.
